using System.Text;

const string canonicalRelative = "platform/text-inspection/src/Ecosystem.TextInspection/TextInspector.cs";
string[] projectionRelatives =
[
    "apps/hub/src/Hub.Core/Generated/Ecosystem.TextInspection/TextInspector.cs",
    "apps/lunet2d/src/Lunet.Core/Generated/Ecosystem.TextInspection/TextInspector.cs"
];

if (args.Length != 1)
{
    Console.Error.WriteLine("Uso: Projection.cs -- --write | --check | --self-test");
    return 2;
}

if (args[0] == "--self-test")
    return SelfTest();

var root = FindRepositoryRoot();
var canonicalPath = Path.Combine(root, canonicalRelative.Replace('/', Path.DirectorySeparatorChar));
var projections = projectionRelatives
    .Select(path => Path.Combine(root, path.Replace('/', Path.DirectorySeparatorChar)))
    .ToArray();

return args[0] switch
{
    "--write" => WriteProjection(canonicalPath, projections),
    "--check" => CheckProjection(canonicalPath, projections),
    _ => 2
};

static string FindRepositoryRoot()
{
    DirectoryInfo? directory = new(Directory.GetCurrentDirectory());
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "ecosystem.json")))
            return directory.FullName;
        directory = directory.Parent;
    }

    throw new InvalidOperationException("Raiz do Ecosystem não encontrada.");
}

static byte[] ExpectedBytes(string canonicalPath)
{
    var canonical = File.ReadAllText(canonicalPath).TrimStart('\uFEFF')
        .Replace("\r\n", "\n", StringComparison.Ordinal)
        .Replace('\r', '\n');

    const string header = """
// <auto-generated>
// GENERATED / DO NOT EDIT.
// Authority: platform/text-inspection/src/Ecosystem.TextInspection/TextInspector.cs
// Regenerate: dotnet run platform/text-inspection/tools/Projection.cs -- --write
// </auto-generated>
""";

    return new UTF8Encoding(encoderShouldEmitUTF8Identifier: false)
        .GetBytes(header.Replace("\r\n", "\n", StringComparison.Ordinal) + "\n" + canonical);
}

static int WriteProjection(string canonicalPath, IReadOnlyList<string> projections, bool quiet = false)
{
    var expected = ExpectedBytes(canonicalPath);
    foreach (var projection in projections)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(projection)!);
        File.WriteAllBytes(projection, expected);
        if (!quiet) Console.WriteLine($"WRITE {projection}");
    }

    return 0;
}

static int CheckProjection(string canonicalPath, IReadOnlyList<string> projections, bool quiet = false)
{
    var expected = ExpectedBytes(canonicalPath);
    var ok = true;

    foreach (var projection in projections)
    {
        if (!File.Exists(projection))
        {
            ok = false;
            if (!quiet) Console.Error.WriteLine($"MISSING {projection}");
            continue;
        }

        if (!File.ReadAllBytes(projection).SequenceEqual(expected))
        {
            ok = false;
            if (!quiet) Console.Error.WriteLine($"DRIFT {projection}");
        }
    }

    if (ok && !quiet) Console.WriteLine("OK text-inspection projections");
    return ok ? 0 : 1;
}

static int SelfTest()
{
    var root = Path.Combine(Path.GetTempPath(), "ecosystem-text-inspection-projection-" + Guid.NewGuid().ToString("N"));
    var canonical = Path.Combine(root, "canonical", "TextInspector.cs");
    string[] projections =
    [
        Path.Combine(root, "hub", "TextInspector.cs"),
        Path.Combine(root, "lunet", "TextInspector.cs")
    ];

    try
    {
        Directory.CreateDirectory(Path.GetDirectoryName(canonical)!);
        File.WriteAllText(canonical, "namespace Example;\npublic static class TextInspector { }\n",
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        Assert(WriteProjection(canonical, projections, quiet: true) == 0, "write inicial falhou");
        Assert(CheckProjection(canonical, projections, quiet: true) == 0, "projeção válida foi rejeitada");

        var first = File.ReadAllBytes(projections[0]);
        File.AppendAllText(projections[0], "// drift\n");
        Assert(CheckProjection(canonical, projections, quiet: true) != 0, "drift não foi detectado");

        Assert(WriteProjection(canonical, projections, quiet: true) == 0, "regeneração falhou");
        Assert(File.ReadAllBytes(projections[0]).SequenceEqual(first), "regeneração não é determinística");

        File.Delete(projections[1]);
        Assert(CheckProjection(canonical, projections, quiet: true) != 0, "projeção ausente não foi detectada");

        Console.WriteLine("OK projection self-test: drift, missing e deterministic regeneration");
        return 0;
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine("FAIL projection self-test: " + ex.Message);
        return 1;
    }
    finally
    {
        if (Directory.Exists(root)) Directory.Delete(root, recursive: true);
    }
}

static void Assert(bool condition, string message)
{
    if (!condition) throw new InvalidOperationException(message);
}
