// Supplemental critical-bug regression corpus. Executes the production legacy importer against real filesystem IO.
import {strict as assert} from 'node:assert';
import {mkdtemp,readFile,writeFile,mkdir,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';import vm from 'node:vm';import {webcrypto} from 'node:crypto';import {File} from 'node:buffer';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';
const root=new URL('../../',import.meta.url),require=createRequire(import.meta.url),JSZip=require('../../vendor/jszip/jszip.min.js');
const context={TextEncoder,TextDecoder,Blob,DOMException,Uint8Array,Map,Set,crypto:webcrypto,JSZip};context.window=context;vm.createContext(context);
for(const file of ['src/core/artifacts.js','src/persistence/export-manifest.js','src/persistence/import.js'])vm.runInContext(await readFile(new URL(file,root),'utf8'),context,{filename:file});
const I=context.UrbeImport,M=context.UrbeExportManifest,enc=s=>new TextEncoder().encode(s),file=(name,value)=>new File([value],name);
const crash=process.argv[2]==='--crash';const temporary=crash?process.argv[3]:await mkdtemp(path.join(tmpdir(),'urbe-import-'));let failure=null;
const adapter={
 async list(){async function walk(folder,prefix=''){let out=[];for(const entry of await readdir(folder,{withFileTypes:true})){const p=prefix+entry.name;if(entry.isDirectory())out.push(...await walk(path.join(folder,entry.name),p+'/'));else out.push(p)}return out}return walk(temporary)},
 async read(v,p){try{return await readFile(path.join(temporary,p),'utf8')}catch(e){if(e.code==='ENOENT')return null;throw e}},
 async readBlob(v,p){try{return new Blob([await readFile(path.join(temporary,p))])}catch(e){if(e.code==='ENOENT')return null;throw e}},
 async write(v,p,value){await this.writeBlob(v,p,new Blob([value]))},
 async writeBlob(v,p,blob){await mkdir(path.dirname(path.join(temporary,p)),{recursive:true});if(failure&&failure(p)){failure=null;throw Object.assign(Error('ENOSPC simulated at real IO boundary'),{code:'ENOSPC'})}await writeFile(path.join(temporary,p),new Uint8Array(await blob.arrayBuffer()));if(crash&&p==='crash-one.md')process.exit(77)},
 async remove(v,p){await rm(path.join(temporary,p),{force:true})}
};
if(crash){const x=await I.inspect([file('crash-one.md','partial'),file('crash-two.md','partial')]);await I.execute(adapter,'Urbe',await I.plan(x,await I.current(adapter,'Urbe')));throw Error('Worker should exit mid-import')}
let count=0;async function test(name,run){await run();count++;console.log('PASS import:',name)}
try{
 await test('single and multiple Markdown, Unicode and binary assets',async()=>{const x=await I.inspect([file('ação 🙂.md','![[figura.png]]'),file('segundo.md','# B'),file('figura.png',new Uint8Array([137,80,0,255]))]);assert.equal(x.documents,2);assert.equal(x.assets,1);const p=await I.plan(x,await I.current(adapter,'Urbe'));await I.execute(adapter,'Urbe',p);assert.equal(await adapter.read('Urbe','ação 🙂.md'),'![[figura.png]]');assert.deepEqual(new Uint8Array(await (await adapter.readBlob('Urbe','figura.png')).arrayBuffer()),new Uint8Array([137,80,0,255]));const replan=await I.plan(x,await I.current(adapter,'Urbe'));assert.equal(replan.operations.length,0);assert.equal(replan.unchanged,3)});
 await test('invalid ZIP and invalid UTF8 preserve the current vault',async()=>{const before=await I.revision(await I.current(adapter,'Urbe'));await assert.rejects(I.inspect([file('bad.zip','oops')]));await assert.rejects(I.inspect([file('bad.md',new Uint8Array([255]))]));assert.equal(await I.revision(await I.current(adapter,'Urbe')),before)});
 await test('conflicting source duplicates require explicit choice; identical selection coalesced',async()=>{const conflict=await I.inspect([file('A.md','a'),file('a.md','b')]);assert.equal(conflict.sourceConflicts.length,1);await assert.rejects(I.plan(conflict,new Map()));const chosen=I.resolveSources(conflict,{'A.md':1});assert.equal(new TextDecoder().decode(chosen.files.get('a.md')),'b');assert.equal((await I.plan(chosen,new Map())).operations.length,1);const x=await I.inspect([file('A.md','a'),file('A.md','a')]);assert.equal(x.files.size,1)});
 await test('conflict cannot execute without a choice; keep and replace',async()=>{const x=await I.inspect([file('segundo.md','# new')]);const p=await I.plan(x,await I.current(adapter,'Urbe'));assert.equal(p.conflicts.length,1);await assert.rejects(I.execute(adapter,'Urbe',p));const keep=await I.plan(x,await I.current(adapter,'Urbe'),{'segundo.md':'keep'});assert.equal(keep.operations.length,0);const replace=await I.plan(x,await I.current(adapter,'Urbe'),{'segundo.md':'replace'});await I.execute(adapter,'Urbe',replace);assert.equal(await adapter.read('Urbe','segundo.md'),'# new')});
 await test('IO/space failure midway rolls back real writes',async()=>{const beforeFiles=await I.current(adapter,'Urbe');for(const p of Array.from(beforeFiles.keys()))if(p.startsWith('.urbe/backup/'))beforeFiles.delete(p);const before=await I.revision(beforeFiles),x=await I.inspect([file('new.md','one'),file('second.md','two')]),p=await I.plan(x,await I.current(adapter,'Urbe'));failure=p=>p==='second.md';await assert.rejects(I.execute(adapter,'Urbe',p));assert.equal(await adapter.read('Urbe','new.md'),null);const after=await I.current(adapter,'Urbe');for(const p of Array.from(after.keys()))if(p.startsWith('.urbe/backup/'))after.delete(p);assert.equal(await I.revision(after),before);assert.equal(await adapter.read('Urbe','segundo.md'),'# new');assert.ok(before)});
 await test('cancellation before and during application restores original bytes',async()=>{const abort=new AbortController();abort.abort();await assert.rejects(I.inspect([file('x.md','x')],{signal:abort.signal}),{name:'AbortError'});const controller=new AbortController(),x=await I.inspect([file('cancel-one.md','x'),file('cancel-two.md','y')]),p=await I.plan(x,await I.current(adapter,'Urbe'));await assert.rejects(I.execute(adapter,'Urbe',p,{signal:controller.signal,progress:()=>controller.abort()}),{name:'AbortError'});assert.equal(await adapter.read('Urbe','cancel-one.md'),null)});
 await test('source stream without seek works',async()=>{let consumed=false;const selected={name:'stream.md',stream:()=>new ReadableStream({start(c){c.enqueue(enc('# stream'));c.close();consumed=true}})};assert.equal((await I.inspect([selected])).documents,1);assert.equal(consumed,true)});
 await test('ZIP signature, hidden metadata, Unicode and verified export',async()=>{const entries=[{path:'ação.md',bytes:enc('# vault')},{path:'.urbe/vault.json',bytes:enc('{"formatVersion":2}')},{path:'.urbe/mapa.json',bytes:enc('{"v":4,"notes":[]}')}];const manifest=await M.build(entries,{}),zip=new JSZip();for(const e of entries)zip.file('Vault/'+e.path,e.bytes);zip.file('Vault/urbe-export.json',JSON.stringify(manifest));const x=await I.inspect([file('not-an-extension.bin',await zip.generateAsync({type:'uint8array'}))]);assert.equal(x.kind,'current-vault');assert.ok(x.files.has('.urbe/mapa.json'));assert.equal(x.files.size,3);zip.file('Vault/ação.md','tampered');await assert.rejects(I.inspect([file('backup.zip',await zip.generateAsync({type:'uint8array'}))]))});
 await test('historical vault and forward-protected vault',async()=>{assert.equal((await I.inspect([{file:file('mapa.json','{"v":1}'),rel:'.urbe/mapa.json'},file('A.md','# A')],{directory:true})).kind,'historical-vault');await assert.rejects(I.inspect([{file:file('vault.json','{"formatVersion":99}'),rel:'.urbe/vault.json'},file('A.md','# A')]))});
 await test('path traversal rejected before ZIP root stripping',async()=>{const zip=new JSZip();zip.file('../evil.md','x');await assert.rejects(I.inspect([file('bad.zip',await zip.generateAsync({type:'uint8array'}))]))});
 await test('stale plan rejected before mutation',async()=>{const x=await I.inspect([file('stale.md','x')]),p=await I.plan(x,await I.current(adapter,'Urbe'));await adapter.write('Urbe','outside.md','changed');await assert.rejects(I.execute(adapter,'Urbe',p));assert.equal(await adapter.read('Urbe','stale.md'),null)});
 await test('extracted migration backup restores only catalogued paths',async()=>{const content='restored 🙂',bytes=enc(content),manifest={version:1,from:1,to:2,files:[{path:'segundo.md',size:content.length,sha256:await M.sha256(bytes)}],absent:['outside.md']};const x=await I.inspect([{file:file('manifest.json',JSON.stringify(manifest)),rel:'manifest.json'},{file:file('segundo.md',bytes),rel:'files/segundo.md'}],{directory:true});assert.equal(x.kind,'backup');assert.equal(x.partial,true);const existing=await I.current(adapter,'Urbe'),p=await I.plan(x,existing,{'segundo.md':'replace','outside.md':'replace'});assert.equal(p.conflicts.length,0);await I.execute(adapter,'Urbe',p);assert.equal(await adapter.read('Urbe','segundo.md'),content);assert.notEqual(await adapter.read('Urbe','ação 🙂.md'),null);assert.equal(await adapter.read('Urbe','outside.md'),null)});
 await test('desktop selection stages sources and exposes only guarded chunk tokens',async()=>{const {createImportSources}=require('../../native/desktop/import-source.js'),cache=await mkdtemp(path.join(tmpdir(),'urbe-native-import-')),provider=createImportSources(cache);try{const selected=await provider.pick([path.join(temporary,'segundo.md'),path.join(temporary,'figura.png')],false);assert.equal(selected.files.length,2);const first=selected.files[0],chunk=await provider.read(selected.token,first.id,0);assert.equal(chunk.done,true);assert.equal(new TextDecoder().decode(chunk.data),'restored 🙂');await assert.rejects(provider.read(selected.token,'../segredo',0));await assert.rejects(provider.read(selected.token,first.id,-1));await provider.release(selected.token);await assert.rejects(provider.read(selected.token,first.id,0));const folder=await provider.pick([temporary],true);assert.ok(folder.files.some(f=>f.path.startsWith('.urbe/')));await provider.release(folder.token)}finally{await provider.close();await rm(cache,{recursive:true,force:true})}});
 await test('actual process death midway recovers in a new session',async()=>{const worker=spawnSync(process.execPath,[fileURLToPath(import.meta.url),'--crash',temporary],{encoding:'utf8'});assert.equal(worker.status,77,worker.stderr);assert.notEqual(await adapter.read('Urbe',I.JOURNAL),null);await I.recover(adapter,'Urbe');assert.equal(await adapter.read('Urbe','crash-one.md'),null);assert.equal(await adapter.read('Urbe','crash-two.md'),null)});
 await test('reopen after interrupted application recovers durable journal',async()=>{const bytes=enc('original'),root='.urbe/backup/import-reopen';await adapter.writeBlob('Urbe',root+'/files/reopen.md',new Blob([bytes]));await adapter.write('Urbe',I.JOURNAL,JSON.stringify({version:1,root,entries:[{path:'reopen.md',backup:root+'/files/reopen.md',size:bytes.length,sha256:await M.sha256(bytes)},{path:'partial.md',backup:null}]}));await adapter.write('Urbe','reopen.md','partial');await adapter.write('Urbe','partial.md','partial');assert.equal(await I.recover(adapter,'Urbe'),true);assert.equal(await adapter.read('Urbe','reopen.md'),'original');assert.equal(await adapter.read('Urbe','partial.md'),null);assert.equal(await I.recover(adapter,'Urbe'),false)});
 await test('unknown metadata never promotes notes into vault replacement',async()=>{await assert.rejects(I.inspect([{file:file('unknown.json','{}'),rel:'.urbe/unknown.json'},file('note.md','x')]))});
 await test('ZIP attachment inside selected folder is preserved',async()=>{const zip=new JSZip();zip.file('inside.md','inside');const bytes=await zip.generateAsync({type:'uint8array'}),x=await I.inspect([file('A.md','note'),{file:file('archive.zip',bytes),rel:'assets/archive.zip'}],{directory:true});assert.equal(x.kind,'documents');assert.equal(x.assets,1);assert.deepEqual(x.files.get('assets/archive.zip'),bytes);assert.equal(x.files.has('inside.md'),false)});
 await test('future or corrupt candidate cannot hide behind an identical path',async()=>{for(const value of ['{\"version\":99}','{'])await assert.rejects(I.inspect([file('A.page.json','{\"version\":1}'),file('A.page.json',value)]))});
 console.log(`${count} production import regression groups passed`);
}finally{await rm(temporary,{recursive:true,force:true})}
