// Port of the frozen UrbeMath catalog; verified by tests/math-oracle.mjs --check.
namespace Urbe.Core;

public static partial class MathEditing
{
    public static IReadOnlyList<MathCommand> Commands { get; } = Array.AsReadOnly<MathCommand>([
        new("\\alpha", "\\alpha", "letra grega α", null),
        new("\\beta", "\\beta", "letra grega β", null),
        new("\\gamma", "\\gamma", "letra grega γ", null),
        new("\\delta", "\\delta", "letra grega δ", null),
        new("\\epsilon", "\\epsilon", "letra grega ϵ", null),
        new("\\varepsilon", "\\varepsilon", "letra grega ε", null),
        new("\\zeta", "\\zeta", "letra grega ζ", null),
        new("\\eta", "\\eta", "letra grega η", null),
        new("\\theta", "\\theta", "letra grega θ", null),
        new("\\vartheta", "\\vartheta", "letra grega ϑ", null),
        new("\\iota", "\\iota", "letra grega ι", null),
        new("\\kappa", "\\kappa", "letra grega κ", null),
        new("\\lambda", "\\lambda", "letra grega λ", null),
        new("\\mu", "\\mu", "letra grega μ", null),
        new("\\nu", "\\nu", "letra grega ν", null),
        new("\\xi", "\\xi", "letra grega ξ", null),
        new("\\pi", "\\pi", "letra grega π", null),
        new("\\rho", "\\rho", "letra grega ρ", null),
        new("\\sigma", "\\sigma", "letra grega σ", null),
        new("\\tau", "\\tau", "letra grega τ", null),
        new("\\upsilon", "\\upsilon", "letra grega υ", null),
        new("\\phi", "\\phi", "letra grega ϕ", null),
        new("\\varphi", "\\varphi", "letra grega φ", null),
        new("\\chi", "\\chi", "letra grega χ", null),
        new("\\psi", "\\psi", "letra grega ψ", null),
        new("\\omega", "\\omega", "letra grega ω", null),
        new("\\Gamma", "\\Gamma", "letra grega Γ", null),
        new("\\Delta", "\\Delta", "letra grega Δ", null),
        new("\\Theta", "\\Theta", "letra grega Θ", null),
        new("\\Lambda", "\\Lambda", "letra grega Λ", null),
        new("\\Xi", "\\Xi", "letra grega Ξ", null),
        new("\\Pi", "\\Pi", "letra grega Π", null),
        new("\\Sigma", "\\Sigma", "letra grega Σ", null),
        new("\\Phi", "\\Phi", "letra grega Φ", null),
        new("\\Psi", "\\Psi", "letra grega Ψ", null),
        new("\\Omega", "\\Omega", "letra grega Ω", null),
        new("\\frac", "\\frac{●}{}", "fração", null),
        new("\\dfrac", "\\dfrac{●}{}", "fração grande", null),
        new("\\sqrt", "\\sqrt{●}", "raiz quadrada", null),
        new("\\sqrt[n]", "\\sqrt[●]{}", "raiz n-ésima", null),
        new("\\binom", "\\binom{●}{}", "binomial", null),
        new("\\sum", "\\sum_{●}^{}", "somatório", null),
        new("\\prod", "\\prod_{●}^{}", "produtório", null),
        new("\\int", "\\int_{●}^{}", "integral", null),
        new("\\iint", "\\iint", "integral dupla", null),
        new("\\oint", "\\oint", "integral de linha", null),
        new("\\lim", "\\lim_{● \\to }", "limite", null),
        new("\\partial", "\\partial", "derivada parcial", null),
        new("\\nabla", "\\nabla", "nabla", null),
        new("\\infty", "\\infty", "infinito", null),
        new("\\mathrm{d}", "\\mathrm{d}●", "d reto", null),
        new("\\cdot", "\\cdot", "produto (ponto)", null),
        new("\\times", "\\times", "vezes", null),
        new("\\div", "\\div", "divisão", null),
        new("\\pm", "\\pm", "mais ou menos", null),
        new("\\mp", "\\mp", "menos ou mais", null),
        new("\\circ", "\\circ", "composição", null),
        new("\\leq", "\\leq", "menor ou igual", null),
        new("\\geq", "\\geq", "maior ou igual", null),
        new("\\neq", "\\neq", "diferente", null),
        new("\\approx", "\\approx", "aproximadamente", null),
        new("\\equiv", "\\equiv", "equivalente", null),
        new("\\sim", "\\sim", "semelhante", null),
        new("\\propto", "\\propto", "proporcional", null),
        new("\\ll", "\\ll", "muito menor", null),
        new("\\gg", "\\gg", "muito maior", null),
        new("\\in", "\\in", "pertence", null),
        new("\\notin", "\\notin", "não pertence", null),
        new("\\subset", "\\subset", "subconjunto", null),
        new("\\subseteq", "\\subseteq", "subconjunto ou igual", null),
        new("\\supset", "\\supset", "contém", null),
        new("\\cup", "\\cup", "união", null),
        new("\\cap", "\\cap", "interseção", null),
        new("\\setminus", "\\setminus", "diferença", null),
        new("\\emptyset", "\\emptyset", "vazio", null),
        new("\\varnothing", "\\varnothing", "vazio", null),
        new("\\forall", "\\forall", "para todo", null),
        new("\\exists", "\\exists", "existe", null),
        new("\\nexists", "\\nexists", "não existe", null),
        new("\\neg", "\\neg", "negação", null),
        new("\\land", "\\land", "e", null),
        new("\\lor", "\\lor", "ou", null),
        new("\\to", "\\to", "seta", null),
        new("\\rightarrow", "\\rightarrow", "seta", null),
        new("\\leftarrow", "\\leftarrow", "seta à esquerda", null),
        new("\\leftrightarrow", "\\leftrightarrow", "seta dupla", null),
        new("\\mapsto", "\\mapsto", "leva em", null),
        new("\\Rightarrow", "\\Rightarrow", "implica", null),
        new("\\implies", "\\implies", "implica", null),
        new("\\iff", "\\iff", "se e somente se", null),
        new("\\Leftrightarrow", "\\Leftrightarrow", "equivalência", null),
        new("\\mathbb", "\\mathbb{●}", "conjuntos (ℝ, ℕ…)", null),
        new("\\mathbb{R}", "\\mathbb{R}", "reais ℝ", null),
        new("\\mathbb{N}", "\\mathbb{N}", "naturais ℕ", null),
        new("\\mathbb{Z}", "\\mathbb{Z}", "inteiros ℤ", null),
        new("\\mathbb{Q}", "\\mathbb{Q}", "racionais ℚ", null),
        new("\\mathbb{C}", "\\mathbb{C}", "complexos ℂ", null),
        new("\\mathcal", "\\mathcal{●}", "caligráfico", null),
        new("\\mathrm", "\\mathrm{●}", "texto reto", null),
        new("\\mathbf", "\\mathbf{●}", "negrito", null),
        new("\\boldsymbol", "\\boldsymbol{●}", "símbolo em negrito", null),
        new("\\text", "\\text{●}", "texto normal", null),
        new("\\operatorname", "\\operatorname{●}", "operador", null),
        new("\\hat", "\\hat{●}", "chapéu", null),
        new("\\bar", "\\bar{●}", "barra", null),
        new("\\overline", "\\overline{●}", "barra longa", null),
        new("\\vec", "\\vec{●}", "vetor", null),
        new("\\dot", "\\dot{●}", "ponto", null),
        new("\\ddot", "\\ddot{●}", "dois pontos", null),
        new("\\tilde", "\\tilde{●}", "til", null),
        new("\\underbrace", "\\underbrace{●}_{}", "chave embaixo", null),
        new("\\left(", "\\left( ● \\right)", "parênteses que crescem", null),
        new("\\left[", "\\left[ ● \\right]", "colchetes que crescem", null),
        new("\\left\\{", "\\left\\{ ● \\right\\}", "chaves que crescem", null),
        new("\\left|", "\\left| ● \\right|", "módulo que cresce", null),
        new("\\langle", "\\langle ● \\rangle", "ângulos", null),
        new("\\lVert", "\\lVert ● \\rVert", "norma", null),
        new("\\ldots", "\\ldots", "reticências", null),
        new("\\cdots", "\\cdots", "reticências centrais", null),
        new("\\vdots", "\\vdots", "reticências verticais", null),
        new("\\ddots", "\\ddots", "reticências diagonais", null),
        new("\\quad", "\\quad", "espaço", null),
        new("\\,", "\\,", "espaço fino", null),
        new("\\sin", "\\sin", "seno", null),
        new("\\cos", "\\cos", "cosseno", null),
        new("\\tan", "\\tan", "tangente", null),
        new("\\log", "\\log", "logaritmo", null),
        new("\\ln", "\\ln", "logaritmo natural", null),
        new("\\exp", "\\exp", "exponencial", null),
        new("\\max", "\\max", "máximo", null),
        new("\\min", "\\min", "mínimo", null),
        new("\\det", "\\det", "determinante", null),
        new("\\gcd", "\\gcd", "mdc", null),
        new("\\begin{pmatrix}", "\\begin{pmatrix} ● & \\\\  &  \\end{pmatrix}", "matriz ( )", null),
        new("\\begin{bmatrix}", "\\begin{bmatrix} ● & \\\\  &  \\end{bmatrix}", "matriz [ ]", null),
        new("\\begin{vmatrix}", "\\begin{vmatrix} ● & \\\\  &  \\end{vmatrix}", "determinante", null),
        new("\\begin{cases}", "\\begin{cases} ● & \\text{se }  \\\\  & \\text{se }  \\end{cases}", "função por partes", null),
        new("\\begin{aligned}", "\\begin{aligned} ● &=  \\\\ &=  \\end{aligned}", "equações alinhadas", null),
        new("\\overset", "\\overset{●}{}", "símbolo acima", null),
        new("\\underset", "\\underset{●}{}", "símbolo abaixo", null),
        new("\\boxed", "\\boxed{●}", "resposta em caixa", null),
        new("\\cancel", "\\cancel{●}", "cancelar", null),
        new("\\therefore", "\\therefore", "portanto", null),
        new("\\because", "\\because", "porque", null),
        new("\\angle", "\\angle", "ângulo", null),
        new("\\perp", "\\perp", "perpendicular", null),
        new("\\parallel", "\\parallel", "paralelo", null),
        new("\\degree", "^\\circ", "grau", null)
    ]);

    public static IReadOnlyList<MathSymbolGroup> Symbols { get; } = Array.AsReadOnly<MathSymbolGroup>([
        new("Básico", Array.AsReadOnly<MathSymbol>([
            new("x²", "^{●}"),
            new("xₙ", "_{●}"),
            new("a⁄b", "\\frac{●}{}"),
            new("√", "\\sqrt{●}"),
            new("( )", "\\left( ● \\right)"),
            new("=", "="),
            new("≠", "\\neq "),
            new("≤", "\\leq "),
            new("≥", "\\geq "),
            new("≈", "\\approx "),
            new("±", "\\pm "),
            new("·", "\\cdot "),
            new("×", "\\times "),
            new("÷", "\\div "),
            new("∞", "\\infty "),
            new("|x|", "\\left| ● \\right|"),
            new("{ }", "\\{ ● \\}"),
            new("…", "\\ldots ")
        ])),
        new("Grego", Array.AsReadOnly<MathSymbol>([
            new("α", "\\alpha "),
            new("β", "\\beta "),
            new("γ", "\\gamma "),
            new("δ", "\\delta "),
            new("ε", "\\varepsilon "),
            new("θ", "\\theta "),
            new("λ", "\\lambda "),
            new("μ", "\\mu "),
            new("π", "\\pi "),
            new("ρ", "\\rho "),
            new("σ", "\\sigma "),
            new("τ", "\\tau "),
            new("φ", "\\varphi "),
            new("ω", "\\omega "),
            new("Δ", "\\Delta "),
            new("Σ", "\\Sigma "),
            new("Ω", "\\Omega "),
            new("Φ", "\\Phi ")
        ])),
        new("Cálculo", Array.AsReadOnly<MathSymbol>([
            new("∫", "\\int "),
            new("∫ₐᵇ", "\\int_{●}^{} "),
            new("∑", "\\sum_{●}^{} "),
            new("∏", "\\prod_{●}^{} "),
            new("lim", "\\lim_{● \\to } "),
            new("∂", "\\partial "),
            new("∇", "\\nabla "),
            new("d/dx", "\\frac{d}{dx}"),
            new("dx", "\\,dx"),
            new("→", "\\to "),
            new("′", "'")
        ])),
        new("Conjuntos", Array.AsReadOnly<MathSymbol>([
            new("∈", "\\in "),
            new("∉", "\\notin "),
            new("⊂", "\\subset "),
            new("⊆", "\\subseteq "),
            new("∪", "\\cup "),
            new("∩", "\\cap "),
            new("∅", "\\emptyset "),
            new("ℕ", "\\mathbb{N}"),
            new("ℤ", "\\mathbb{Z}"),
            new("ℚ", "\\mathbb{Q}"),
            new("ℝ", "\\mathbb{R}"),
            new("ℂ", "\\mathbb{C}"),
            new("∀", "\\forall "),
            new("∃", "\\exists "),
            new("¬", "\\neg "),
            new("∧", "\\land "),
            new("∨", "\\lor ")
        ])),
        new("Setas", Array.AsReadOnly<MathSymbol>([
            new("→", "\\to "),
            new("←", "\\leftarrow "),
            new("↔", "\\leftrightarrow "),
            new("↦", "\\mapsto "),
            new("⇒", "\\Rightarrow "),
            new("⇐", "\\Leftarrow "),
            new("⇔", "\\iff "),
            new("↑", "\\uparrow "),
            new("↓", "\\downarrow ")
        ]))
    ]);

    public static IReadOnlyList<MathSymbol> Templates { get; } = Array.AsReadOnly<MathSymbol>([
            new("Fração", "\\frac{●}{}"),
            new("Raiz n-ésima", "\\sqrt[●]{}"),
            new("Potência", "{●}^{}"),
            new("Integral definida", "\\int_{●}^{} f(x)\\,dx"),
            new("Somatório", "\\sum_{i=●}^{n} "),
            new("Limite", "\\lim_{x \\to ●} "),
            new("Derivada", "\\frac{d●}{dx}"),
            new("Derivada parcial", "\\frac{\\partial ●}{\\partial x}"),
            new("Matriz 2×2", "\\begin{pmatrix} ● & b \\\\ c & d \\end{pmatrix}"),
            new("Matriz 3×3", "\\begin{bmatrix} ● & & \\\\ & & \\\\ & & \\end{bmatrix}"),
            new("Determinante", "\\begin{vmatrix} ● & b \\\\ c & d \\end{vmatrix}"),
            new("Sistema", "\\begin{cases} ● \\\\ \\end{cases}"),
            new("Por partes", "f(x)=\\begin{cases} ● & \\text{se } x<0 \\\\ & \\text{se } x\\ge 0 \\end{cases}"),
            new("Alinhado", "\\begin{aligned} ● &= \\\\ &= \\end{aligned}"),
            new("Binomial", "\\binom{●}{k}"),
            new("Vetor", "\\vec{●}"),
            new("Norma", "\\lVert ● \\rVert"),
            new("Resposta", "\\boxed{●}")
    ]);
}
